---
- name: Install containerd and its deps
  ansible.builtin.apt:
    name: containerd
    state: present
  become: true

- name: Copy containerd config file
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
  become: true
  notify: Restart containerd service
