---
- name: Enable brfilters kernel mod on the pi
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present
  become: true
  notify: Reboot system

- name: Enable memory cgroup
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  become: true
  notify: Reboot system

- name: Enable ipv4 packet forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
  become: true
  notify: Reboot system
