---
- name: "Extract CNI libs {{ cni_libs_version }} for arm64 into /opt/cni/bin"
  ansible.builtin.unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/{{ cni_libs_version }}/cni-plugins-linux-arm64-{{ cni_libs_version }}.tgz"
    remote_src: true
    dest: /opt/cni/bin
  become: true
